### PR TITLE
Fix #440. Add tests for h5write/read with filename

### LINKED ISSUE #440: h5write fails for new file in Julia 0.6
Attempting to run some code of ours that (in Julia 0.4.7) was able to successfully open a new HDF5 file and write to it using h5write. Now in Julia 0.6 it fails.

Julia version: 0.6
HDF5 version: 0.8.4
JLD version: 0.8.1

Example code:

```
julia> test = zeros(Float64, 2, 2)
2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

julia> h5write("testfile.h5", "testsection", test)
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140264843021376:
  #000: ../../../src/H5F.c line 439 in H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: ../../../src/H5Fint.c line 554 in H5F_is_hdf5(): unable to open file
    major: Low-level I/O
    minor: Unable to initialize object
  #002: ../../../src/H5FD.c line 993 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: ../../../src/H5FDsec2.c line 339 in H5FD_sec2_open(): unable to open file: name = 'testfile.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
ERROR: Cannot access file testfile.h5
Stacktrace:
 [1] h5f_is_hdf5(::String) at /home/emc/.julia/v0.6/HDF5/src/HDF5.jl:2179
 [2] #h5open#3(::Bool, ::Function, ::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::HDF5.HDF5Properties, ::HDF5.HDF5Properties) at /home/emc/.julia/v0.6/HDF5/src/HDF5.jl:592
 [3] (::HDF5.#kw##h5open)(::Array{Any,1}, ::HDF5.#h5open, ::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::HDF5.HDF5Properties, ::HDF5.HDF5Properties) at ./<missing>:0
 [4] #h5open#4(::Bool, ::Function, ::String, ::String) at /home/emc/.julia/v0.6/HDF5/src/HDF5.jl:643
 [5] h5write(::String, ::String, ::Array{Float64,2}) at /home/emc/.julia/v0.6/HDF5/src/HDF5.jl:682
```
Seems to be because h5write calls h5open using the "r+" mode. Changing the mode to "w" and just running the commands by hand at least gets it open:

```
julia> fid = h5open("testfile.h5", "w")
HDF5 data file: testfile.h5

julia> write(fid, "testsection", test)

julia> close(fid)
```
However, I've run into some other problems with our code that aren't solved as simply, even if I can manage to get the files open.

Thanks!

### PR DESCRIPTION
**Pull request by una-dinosauria**
* It seems like https://github.com/JuliaIO/HDF5.jl/pull/394/files#diff-02840edcdbd42c5b41e89b3f700b9a28L674 inadvetently changed the API of `h5write`, such that the file is expected to exist now.
* I'm adding tests to test for `h5write` and `h5read` with a filename as well.

### CODE REVIEW

**Comment by musm** [comment]
Thanks, is it possible to reuse the previous file name that are used in the test, e.g. https://github.com/una-dinosauria/HDF5.jl/blob/d7179586e2aa590c349d15fa6c95f0b9958ee284/test/plain.jl#L8? 
Otherwise the new test file should be closed and deleted at the end of testing.

**Comment by una-dinosauria** [comment]
`fn` exists until the end, so a new `h5write` will have to create  another file. I'll add the closing and removing of `fn2`.

**Comment by una-dinosauria** [comment]
Nevermind, I'm reusing the name now

File: test/plain.jl [hunk 1]
```diff
@@ -112,6 +112,7 @@ Wa = Dict("a" => 1, "b" => 2)
 h5write(fn, "newgroup/W", W)
 h5writeattr(fn, "newgroup/W", Wa)
 
+
```
Comment (musm) [inline test/plain.jl]: extra space?

**Comment by musm** [comment]
will merge in 24 hours, thanks!
