### PR TITLE
Fix #618, treat create-write operation as transaction

### LINKED ISSUE #618: h5write will create file and dataset even if write fails
If you try to use `h5write` to make a dataset, and do something that errors (for example, write the transpose of an array), it will fail, but still make the dataset. This prevents the write after correcting your mistake unless you know what happened and delete the dataset:

```julia
julia> h5write("vertical_east.h5", "up_2018", permutedims(up.image))

julia> a = rand(2, 2)
2×2 Array{Float64,2}:
 0.587     0.230941
 0.851558  0.542216

julia> h5write("badwrite.h5", "test", a')
ERROR: MethodError: no method matching strides(::Adjoint{Float64,Array{Float64,2}})
Closest candidates are:
  strides(::PyBuffer) at /home/scott/.julia/packages/PyCall/ttONZ/src/pybuffer.jl:96
  strides(::SubArray) at subarray.jl:304
  strides(::FFTW.FakeArray) at /home/scott/.julia/packages/FFTW/qqcBj/src/fft.jl:120
  ...
Stacktrace:
 [1] stride(::Adjoint{Float64,Array{Float64,2}}, ::Int64) at ./abstractarray.jl:396
 [2] h5d_write(::Int64, ::Int64, ::Adjoint{Float64,Array{Float64,2}}, ::Int64) at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:2040
 [3] writearray(::HDF5Dataset, ::Int64, ::Adjoint{Float64,Array{Float64,2}}) at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:1907
 [4] _d_write(::HDF5File, ::String, ::Adjoint{Float64,Array{Float64,2}}) at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:1716
 [5] d_write(::HDF5File, ::String, ::Adjoint{Float64,Array{Float64,2}}) at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:1723
 [6] write(::HDF5File, ::String, ::Adjoint{Float64,Array{Float64,2}}) at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:1750
 [7] h5write(::String, ::String, ::Adjoint{Float64,Array{Float64,2}}) at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:706
 [8] top-level scope at REPL[49]:1

julia> h5write("badwrite.h5", "test", a)
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 0:
  #000: H5D.c line 145 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: H5Dint.c line 326 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: H5L.c line 1572 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: H5L.c line 1813 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #004: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: H5L.c line 1608 in H5L__link_cb(): name already exists
    major: Links
    minor: Object already exists
ERROR: Error creating dataset //test
Stacktrace:
 [1] error(::String, ::String, ::String, ::String) at ./error.jl:42
 [2] h5d_create at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:2279 [inlined]
 [3] d_create(::HDF5File, ::String, ::HDF5Datatype, ::HDF5Dataspace, ::HDF5Properties, ::HDF5Properties, ::HDF5Properties, ::HDF5Properties) at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:924 (repeats 2 times)
 [4] _d_create(::HDF5File, ::String, ::Array{Float64,2}) at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:1693
 [5] d_create at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:1700 [inlined]
 [6] _d_write(::HDF5File, ::String, ::Array{Float64,2}) at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:1714
 [7] d_write at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:1723 [inlined]
 [8] write at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:1750 [inlined]
 [9] h5write(::String, ::String, ::Array{Float64,2}) at /home/scott/.julia/packages/HDF5/12i6f/src/HDF5.jl:706
 [10] top-level scope at REPL[50]:1

```

```julia
julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 28
```

### PR DESCRIPTION
**Pull request by jmert**
On a failed write that implicitly creates a new dataset/attribute,
delete the just-created object before continuing.

This makes following-up after an interactive error much more
ergonomic.

### CODE REVIEW

**Comment by musm** [comment]
LGTM although can we add the test case in the linked issue, since the test added here are testing  a different path (these tests also pass on master).

File: src/HDF5.jl [hunk 1]
```diff
@@ -1415,6 +1415,9 @@ function d_write(parent::Union{File,Group}, name::String, data; pv...)
     obj, dtype = d_create(parent, name, data; pv...)
```
Comment (musm) [inline src/HDF5.jl:1415]: We should probably also add something like the following (perhaps ArgumentError)  here and below
```suggestion
    haskey(parent, name) && error( name, " already exists")
```

to prevent errors that get thrown like the following
```julia
julia> hid = h5open(tempname(), "w")
HDF5 data file: C:\Users\Mus\AppData\Local\Temp\jl_zDsvcXjFU3

julia> write(hid, "A", rand(3,3))

julia> write(hid, "A", rand(3,3))
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: E:/mingwbuild/mingw-w64-hdf5/src/hdf5-1.10.5/src/H5D.c line 145 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: E:/mingwbuild/mingw-w64-hdf5/src/hdf5-1.10.5/src/H5Dint.c line 329 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: E:/mingwbuild/mingw-w64-hdf5/src/hdf5-1.10.5/src/H5L.c line 1557 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: E:/mingwbuild/mingw-w64-hdf5/src/hdf5-1.10.5/src/H5L.c line 1798 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #004: E:/mingwbuild/mingw-w64-hdf5/src/hdf5-1.10.5/src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: E:/mingwbuild/mingw-w64-hdf5/src/hdf5-1.10.5/src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: E:/mingwbuild/mingw-w64-hdf5/src/hdf5-1.10.5/src/H5L.c line 1593 in H5L__link_cb(): name already exists
    major: Links
    minor: Object already exists
ERROR: Error creating dataset //A
Stacktrace:
  [1] error(::String, ::String, ::String, ::String)
    @ Base .\error.jl:42
  [2] h5d_create
    @ ~\.julia\dev\HDF5\src\api.jl:158 [inlined]
  [3] d_create(parent::HDF5.File, path::String, dtype::HDF5.Datatype, dspace::HDF5.Dataspace; pv::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ HDF5 ~\.julia\dev\HDF5\src\HDF5.jl:733
  [4] d_create
    @ ~\.julia\dev\HDF5\src\HDF5.jl:730 [inlined]
  [5] d_create(parent::HDF5.File, name::String, data::Matrix{Float64}; pv::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ HDF5 ~\.julia\dev\HDF5\src\HDF5.jl:1405
  [6] d_create
    @ ~\.julia\dev\HDF5\src\HDF5.jl:1402 [inlined]
  [7] d_write(parent::HDF5.File, name::String, data::Matrix{Float64}; pv::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ HDF5 ~\.julia\dev\HDF5\src\HDF5.jl:1424
  [8] d_write
    @ ~\.julia\dev\HDF5\src\HDF5.jl:1424 [inlined]
  [9] #write#45
    @ ~\.julia\dev\HDF5\src\HDF5.jl:1470 [inlined]
 [10] write(parent::HDF5.File, name::String, data::Matrix{Float64})
    @ HDF5 ~\.julia\dev\HDF5\src\HDF5.jl:1470
 [11] top-level scope
    @ REPL[3]:1


```

Comment (musm) [reply src/HDF5.jl:1415]: Although this is probably  best left to a separate PR (I think this is systemic with other methods, that I haven't fully looked at, when called on twice).

Comment (musm) [reply src/HDF5.jl:1415]: E.g. all the high level create/write methods also suffer from the same issue.

**Comment by jmert** [comment]
> LGTM although can we add the test case in the linked issue, since the test added here looks to be testing a different path (the added tests also pass on master).
> 
> E.g.
> 
> ```julia
> A = randn(3,3)
> @test_throws Exception write(hid, "A", A')
> write(hid, "A", A) # test this doesn't error
> ```

Ah, good catch! I was thinking in terms of `d_write` where we just loosened the type signature, and I didn't read carefully enough to notice the `MethodError` was from not matching `write` rather than not matching `datatype` like I'd assumed.

I'll just change the tests to a transpose matrix like you suggest.

File: src/HDF5.jl (hunk 1 above)
Comment (jmert) [reply src/HDF5.jl:1425]: Yeah, I think that'll be part of the method cleanup that needs to happen.
